{{- if not (eq .Values.gotosocial.dbType "sqlite")}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gotosocial.fullname" . }}
  labels:
    {{- include "gotosocial.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gotosocial.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gotosocial.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gotosocial.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: GTS_HOST
            value: {{ .Values.gotosocial.host }}
          {{- if or (eq .Values.gotosocial.dbType "ephemeral") (eq .Values.gotosocial.dbType "sqlite")}}
          - name: GTS_DB_TYPE
            value: sqlite
          - name: GTS_DB_ADDRESS
            value: /data/sqlite.db
          {{- else if eq .Values.gotosocial.dbType "postgresql-depends" }}
          - name: GTS_DB_TYPE
            value: postgres
          - name: GTS_DB_ADDRESS
            value: gotosocial-postgresql-hl
          - name: GTS_DB_USER
            value: {{ .Values.postgresql.global.postgresql.auth.username }}
          - name: GTS_DB_DATABASE
            value: {{ .Values.postgresql.global.postgresql.auth.database }}
          - name: GTS_DB_PASSWORD
            value: {{ .Values.postgresql.global.postgresql.auth.password }}
          {{- else if eq .Values.gotosocial.dbType "postgresql-ext" }}
          - name: GTS_DB_TYPE
            value: postgres
          - name: GTS_DB_ADDRESS
            value: {{ .Values.extdb.hostname }}
          - name: GTS_DB_USER
            value: {{ .Values.extdb.username }}
          - name: GTS_DB_DATABASE
            value: {{ .Values.extdb.database }}
          - name: GTS_DB_PASSWORD
            value: {{ .Values.extdb.password }}
          {{- end }}
          {{- toYaml .Values.gotosocial.extraConfig | nindent 10 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if or (eq .Values.gotosocial.dbType "ephemeral") (eq .Values.gotosocial.dbType "sqlite")}}
          volumeMounts:
          - mountPath: /data
            name: data
      {{- end }}
      {{- if eq .Values.gotosocial.dbType "ephemeral"}}
      volumes:
      - name: data
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end}}
